name: Combined Build and Semantic Release

on:
  push:
    branches:
      - main

env: 
  VITE_API_URL: ${{secrets.VITE_API_URL}}
  VITE_MIX_PANEL_TOKEN: ${{secrets.VITE_MIX_PANEL_TOKEN}}
  VITE_ENABLE_MIX_PANEL: ${{secrets.VITE_ENABLE_MIX_PANEL}}
  VITE_API_TIMEOUT: ${{secrets.VITE_API_TIMEOUT}}

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # - name: Install Dependencies
      #   run: |
      #     yarn install

      - name: Build Tauri App on MacOS
        if: runner.os == 'macos-latest'
        run: |
          TAURI_PRIVATE_KEY="${{ secrets.TAURI_PRIVATE_KEY }}"
          TAURI_KEY_PASSWORD="${{ secrets.TAURI_KEY_PASSWORD }}" 
          APPLE_SIGNING_IDENTITY="${{ secrets.APPLE_SIGNING_IDENTITY }}"
          APPLE_CERTIFICATE="${{ secrets.APPLE_CERTIFICATE }}"
          APPLE_CERTIFICATE_PASSWORD="${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" 
          yarn install
          yarn tauri build --debug
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build Tauri App on Windows
        if: runner.os == 'windows-latest'
        run: |
          $TAURI_PRIVATE_KEY="${{ secrets.TAURI_PRIVATE_KEY }}"
          $TAURI_KEY_PASSWORD="${{ secrets.TAURI_KEY_PASSWORD }}" 
          yarn install
          yarn tauri build --debug
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      # - name: Archive
      #   if: runner.os == 'macOS' # Adjust path based on OS
      #   run: |
      #     zip -r sparrow-app_1.0.0_x64.dmg /Users/runner/work/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/dmg/sparrow-app_1.0.0_x64.dmg

      # - name: Archive
      #   if: runner.os == 'Windows' # Adjust path based on OS
      #   run: |
      #     # Adjust the path for Windows
      #     # For example:
      #     # zip -r sparrow-app_1.0.0_x64.zip C:\path\to\your\app.exe

      - name: Fetch Version from package.json
        id: fetch-version
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
