
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install Windows SDK
        run: Invoke-WebRequest -Uri https://aka.ms/winsdk/10/latest/SdkSetup.exe -OutFile $env:TEMP\SdkSetup.exe
        shell: powershell

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Install dependencies
        run: |
            yarn cache clean
            npm install -g pnpm
            # pnpm install
            yarn install
            # yarn tauri build --debug
      - name: Build Tauri App
        run: |
            $TAURI_PRIVATE_KEY="${{ secrets.TAURI_PRIVATE_KEY }}"
            $TAURI_KEY_PASSWORD="${{ secrets.TAURI_KEY_PASSWORD }}" 
            yarn tauri build --debug
        env:
           TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
           TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
           GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Extract Secret Value
        id: extract_secret
        run: |
         SECRET_VALUE=$(cat D:/a/sparrow_app/sparrow_app/src-tauri/target/debug/bundle/msi/sparrow-app_0.0.0_x64_en-US.msi.zip.sig)
         echo "::set-output name=secret_value::$SECRET_VALUE"
        # Extracting the secret value from the specified file
        # Modify this command according to your requirements to extract the value from the file
        # Here, we're assuming the secret is stored as plain text in the file
        
      
      - name: Update Secret
        uses: actions/github-script@v4
        with:
         github-token: ${{ secrets.MY_GITHUB_TOKEN }}
         script: |
          const newSecretValue = process.env['SECRET_VALUE'];
          github.repos.createOrUpdateSecretForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'NEW_SECRET_VALUE',
            encrypted_value: newSecretValue
          });
