name: Update Secret in sparrow-api

on:
  push:
    branches:
      - main

jobs:
  update-secret:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Public Key
      id: get-key
      run: |
        url="https://api.github.com/repos/OWNER/REPO/actions/secrets/public-key"
        headers=(
         "Accept: application/vnd.github.v3+json"
         "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}"
         "X-GitHub-Api-Version: 2022-11-28"
        )
        response=$(curl -sSL -H "${headers[@]}" $url)
        echo "Response: $response"

      shell: bash



        # # Extract the public key and key ID from the response JSON
        # $publicKey = $response.Content | ConvertFrom-Json
        # $publicKeyBase64 = $publicKey.key
        # $keyId = $publicKey.key_id

        # # Set environment variables for later use
        # echo "PUBLIC_KEY=$publicKeyBase64" >> $env:GITHUB_ENV
        # echo "KEY_ID=$keyId" >> $env:GITHUB_ENV

      # shell: pwsh
