name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install Windows SDK
        run: Invoke-WebRequest -Uri https://aka.ms/winsdk/10/latest/SdkSetup.exe -OutFile $env:TEMP\SdkSetup.exe
        shell: powershell

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Install dependencies
        run: |
            yarn cache clean
            npm install -g pnpm
            # pnpm install
            yarn install
            # yarn tauri build --debug
      - name: Build Tauri App
        run: |
            $TAURI_PRIVATE_KEY="${{ secrets.TAURI_PRIVATE_KEY }}"
            $TAURI_KEY_PASSWORD="${{ secrets.TAURI_KEY_PASSWORD }}" 
            yarn tauri build --debug
        env:
           TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
           TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
           GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

         
      - name: Extract and Update Secret
        run: |
            # Get the content of the file
            $ENCODED_TOKEN = Get-Content 'D:\a\sparrow_app\sparrow_app\src-tauri\target\debug\bundle\msi\sparrow-app_0.0.0_x64_en-US.msi.zip.sig' -Raw

            # Define the API endpoint
            $apiUrl = "https://api.github.com/repos/pratikshinde590/sparrow-api/actions/secrets/SPARROW_APP_MSI_SIG"

            # Define the headers
            $headers = @{
                "Authorization" = "Bearer ${{ secrets.MY_GITHUB_TOKEN }}"  # Replace with your GitHub personal access token
                "Accept" = "application/vnd.github.v3+json"
            }

            # Define the request body
            $body = @{
                encrypted_value = $ENCODED_TOKEN
                key_id = ""
            } | ConvertTo-Json

            # Make the API request
            Invoke-RestMethod -Uri $apiUrl -Method Put -Headers $headers -Body $body
        env:
          YOUR_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}


               

      - name: Fetch Version from package.json
        id: fetch-version
        run: echo "::set-output name=version::$(jq -r .version package.json)"
            
      - name: Rename .exe file with version
        run: mv D:/a/sparrow_app/sparrow_app/src-tauri/target/debug/bundle/nsis/sparrow-app_0.0.0_x64-setup.exe "D:/a/sparrow_app/sparrow_app/src-tauri/target/debug/bundle/nsis/sparrow-app_${{ steps.fetch-version.outputs.version }}_x64-setup.exe"

      - name: Rename .msi file with version
        run: mv D:/a/sparrow_app/sparrow_app/src-tauri/target/debug/bundle/msi/sparrow-app_0.0.0_x64_en-US.msi "D:/a/sparrow_app/sparrow_app/src-tauri/target/debug/bundle/msi/sparrow-app_${{ steps.fetch-version.outputs.version }}_x64_en-US.msi"
    

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} #github_token
