name: Update Updater Endpoint

on:
  push:
    branches:
      - main

jobs:
  update_updater_endpoint:
    name: Update Updater Endpoint
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read tauri.conf.json
        id: read_file
        run: |
          $content = Get-Content src-tauri/tauri.conf.json -Raw
          Write-Output $content
        shell: pwsh

      - name: Update updater endpoint in JSON file
        run: |
          $content = Get-Content src-tauri/tauri.conf.json -Raw
          $newContent = $content -replace '"https://api.sparrowapp.dev/updater/{{target}}/{{arch}}/{{current_version}}"', '"https://${{ secrets.UPDATER_ENDPOINT }}/updater/{{target}}/{{arch}}/{{current_version}}"'
          Set-Content -Path src-tauri/tauri.conf.json -Value $newContent
        shell: pwsh

      - name: Print updated tauri.conf.json
        run: |
          $content = Get-Content src-tauri/tauri.conf.json -Raw
          Write-Output $content
        shell: pwsh

      - name: Commit changes
        run: |
          git config --global user.name "pratik"
          git config --global user.email "pratik.shinde@techdome.net.in"
          git add src-tauri/tauri.conf.json
          git commit -m "Update updater endpoint"
          git push
        shell: pwsh
